# Pandas Assignment.

### 1. Create a data series with marks of students : 75, 80, 79, 60

In [5]:
import pandas as pd
UNV=pd.read_csv("data for panda exercise (1).csv")
UNV

,Student Code,Degree,Student Name,Mid,Quiz 1,Quiz 2,Best of Quizzes,Assignment 1,Assignment 2,Best of Assignments,Total Sessional (50),Final (50),Total (100),Grade
0,022-14-19987,BS(CS),Abdul Basit,28,8.0,3.0,8,7.0,9.0,9,45,25.0,70,B
1,022-14-110233,BS(CS),Adeel Ahmed,17,NaN,5.0,5,8.0,10.0,10,32,18.0,50,F
2,022-14-110585,BS(CS),Afrah Zareen,18,5.0,2.0,5,8.0,10.0,10,33,30.0,63,C
3,022-14-19718,BS(CS),Ahmed Ali Raza,14,7.0,2.0,7,NaN,2.0,2,23,23.0,46,F
4,022-14-110648,BS(CS),Ahsan Ali Vohra,27,7.0,6.0,7,7.0,9.0,9,43,34.0,77,B
5,022-14-110232,BS(CS),Ameer Hamza,25,9.0,6.0,9,8.0,10.0,10,44,27.0,71,B
6,022-14-110588,BS(CS),Anas Ali Khan,28,5.0,6.0,6,8.0,10.0,10,44,30.0,74,B
7,022-14-110388,BS(CS),Aneebullah Niazi,26,9.0,6.0,9,8.0,10.0,10,45,40.0,85,A
8,022-14-110601,BS(CS),Areesha Sohail,19,9.0,4.0,9,7.0,9.0,9,37,24.0,61,C
9,022-14-110599,BS(CS),Arsalan,28,8.0,6.0,8,8.0,NaN,8,44,40.0,84,A
10,022-14-110214,BS(CS),Fatima Haider Warsi,30,8.0,7.0,8,8.0,NaN,8,46,45.0,91,A
11,022-14-110591,BS(CS),Habib Ullah,28,8.0,5.0,8,5.0,NaN,5,41,35.0,76,B
12,022-15-110994,BS(CS),Hafiza Tooba Akbani,23,7.0,5.0,7,8.0,10.0,10,40,33.0,73,B
13,022-14-110600,BS(CS),Hamza Abdul Jabbar,24,8.0,4.0,8,8.0,10.0,10,42,25.0,67,C
14,022-14-110389,BS(CS),Hareem Afshan,21,7.0,4.0,7,6.0,8.0,8,36,29.0,65,C
15,022-14-19916,BS(CS),Haseeb Sajid,18,NaN,NaN,0,NaN,NaN,0,18,NaN,18,F
16,022-14-110596,BS(CS),Hassam Ahmed,23,5.0,5.0,5,7.0,9.0,9,37,35.0,72,B
17,022-14-110396,BS(CS),Khalid Anwer,20,8.0,5.0,8,9.0,11.0,11,39,31.0,70,B
18,022-14-110223,BS(CS),Madiha Jabeen,16,5.0,2.0,5,8.0,10.0,10,31,29.0,60,C
19,022-14-110222,BS(CS),Mohammad Hunain,27,9.0,6.0,9,8.0,10.0,10,46,45.0,91,A
20,022-14-110412,BS(CS),Muhammad Aamir,24,7.0,6.0,7,7.0,9.0,9,40,31.0,71,B
21,022-14-110593,BS(CS),Muhammad Abdul Rehman Siddiqui,20,9.0,6.0,9,9.0,11.0,11,40,20.0,60,C
22,022-14-110398,BS(CS),Muhammad Abdullah,20,7.0,6.0,7,7.0,NaN,7,34,23.0,57,F
23,022-14-19983,BS(CS),Muhammad Ali Iqbal,26,5.0,NaN,5,8.0,10.0,10,41,21.0,62,C
24,022-14-110215,BS(CS),Muhammad Bilal,28,5.0,4.0,5,9.0,11.0,11,44,33.0,77,B
25,022-14-110105,BS(CS),Muhammad Faraz,26,9.0,6.0,9,8.0,10.0,10,45,41.0,86,A
26,022-14-110370,BS(CS),Muhammad Ghazali Faridi,27,6.0,NaN,6,6.0,8.0,8,41,24.0,65,C
27,022-14-110452,BS(CS),Muhammad Osama Khan,27,8.0,6.0,8,8.0,10.0,10,45,26.0,71,B
28,022-14-110387,BS(CS),Muhammad Saqib Intizar,22,6.0,6.0,6,9.0,11.0,11,39,18.0,57,F
29,022-14-110217,BS(CS),Muhammad Shahroz Khurshid,17,7.0,1.0,7,6.0,NaN,6,30,9.0,39,F
30,022-14-110401,BS(CS),Muhammad Shozab,23,8.0,6.0,8,9.0,NaN,9,40,32.0,72,B
31,022-14-110231,BS(CS),Muhammad Taha Hasnain,27,7.0,5.0,7,10.0,NaN,10,44,29.0,73,B
32,022-14-110035,BS(CS),Muhammad Wajahat Khan,9,NaN,2.0,2,8.0,10.0,10,21,8.0,29,F
33,022-14-19919,BS(CS),Muhammad Younus Baig,20,4.0,2.0,4,8.0,10.0,10,34,17.0,51,F
34,022-14-110413,BS(CS),Nazeer Bin Zafar,25,9.0,6.0,9,8.0,10.0,10,44,42.0,86,A
35,022-14-19923,BS(CS),Rabi Ahmed,20,8.0,5.0,8,NaN,10.0,10,38,28.0,66,C
36,022-14-110582,BS(CS),Rida Nasim,25,9.0,5.0,9,9.0,NaN,9,43,27.0,70,B
37,022-14-110230,BS(CS),Sadaf Nosheen,27,9.0,5.0,9,9.0,NaN,9,45,30.0,75,B
38,022-14-110229,BS(CS),Sadaquat Rafique,9,6.0,6.0,6,5.0,7.0,7,22,17.0,39,F
39,022-14-110107,BS(CS),Sania Iqbal,28,4.0,4.0,4,9.0,11.0,11,43,25.0,68,C
40,022-14-110584,BS(CS),Sharif Taqi,27,9.0,6.0,9,8.0,10.0,10,46,35.0,81,A
41,022-14-110225,BS(CS),Shariqa Ahmad,20,7.0,6.0,7,8.0,10.0,10,37,20.0,57,F
42,022-14-110587,BS(CS),Sumbul Rehman,28,5.0,6.0,6,8.0,10.0,10,44,23.0,67,C
43,022-14-110451,BS(CS),Syed Faizan Uddin,28,9.0,4.0,9,6.0,8.0,8,45,34.0,79,B
44,022-14-110589,BS(CS),Syed Sohaib,25,7.0,5.0,7,9.0,NaN,9,41,22.0,63,C
45,022-14-110400,BS(CS),Syeda Sabika Raza,27,9.0,6.0,9,9.0,NaN,9,45,35.0,80,A
46,022-14-19911,BS(CS),Usman Khan,25,8.0,5.0,8,8.0,10.0,10,43,22.0,65,C
47,022-14-110219,BS(CS),Waqar Ahmed,11,9.0,5.0,9,5.0,7.0,7,27,19.0,46,F

In [11]:
print(pd.Series.loc)

<property object at 0x00000000089C8638>

### 2. Create a data frame with name of students, id and marks

In [8]:
pd.DataFrame(UNV,columns=['Student Name','Student Code','Total (100)'])

                      Student Name   Student Code  Total (100)
0                      Abdul Basit   022-14-19987           70
1                      Adeel Ahmed  022-14-110233           50
2                     Afrah Zareen  022-14-110585           63
3                   Ahmed Ali Raza   022-14-19718           46
4                  Ahsan Ali Vohra  022-14-110648           77
5                      Ameer Hamza  022-14-110232           71
6                    Anas Ali Khan  022-14-110588           74
7                 Aneebullah Niazi  022-14-110388           85
8                   Areesha Sohail  022-14-110601           61
9                          Arsalan  022-14-110599           84
10             Fatima Haider Warsi  022-14-110214           91
11                     Habib Ullah  022-14-110591           76
12             Hafiza Tooba Akbani  022-15-110994           73
13              Hamza Abdul Jabbar  022-14-110600           67
14                   Hareem Afshan  022-14-110389           65
15                    Haseeb Sajid   022-14-19916           18
16                    Hassam Ahmed  022-14-110596           72
17                    Khalid Anwer  022-14-110396           70
18                   Madiha Jabeen  022-14-110223           60
19                 Mohammad Hunain  022-14-110222           91
20                  Muhammad Aamir  022-14-110412           71
21  Muhammad Abdul Rehman Siddiqui  022-14-110593           60
22               Muhammad Abdullah  022-14-110398           57
23              Muhammad Ali Iqbal   022-14-19983           62
24                  Muhammad Bilal  022-14-110215           77
25                  Muhammad Faraz  022-14-110105           86
26         Muhammad Ghazali Faridi  022-14-110370           65
27             Muhammad Osama Khan  022-14-110452           71
28          Muhammad Saqib Intizar  022-14-110387           57
29       Muhammad Shahroz Khurshid  022-14-110217           39
30                 Muhammad Shozab  022-14-110401           72
31           Muhammad Taha Hasnain  022-14-110231           73
32           Muhammad Wajahat Khan  022-14-110035           29
33            Muhammad Younus Baig   022-14-19919           51
34                Nazeer Bin Zafar  022-14-110413           86
35                      Rabi Ahmed   022-14-19923           66
36                      Rida Nasim  022-14-110582           70
37                   Sadaf Nosheen  022-14-110230           75
38                Sadaquat Rafique  022-14-110229           39
39                     Sania Iqbal  022-14-110107           68
40                     Sharif Taqi  022-14-110584           81
41                   Shariqa Ahmad  022-14-110225           57
42                   Sumbul Rehman  022-14-110587           67
43               Syed Faizan Uddin  022-14-110451           79
44                     Syed Sohaib  022-14-110589           63
45               Syeda Sabika Raza  022-14-110400           80
46                      Usman Khan   022-14-19911           65
47                     Waqar Ahmed  022-14-110219           46

### 3. Now read the file 'data.csv' in panda

In [9]:
UNV=pd.read_csv("data for panda exercise (1).csv")
UNV

,Student Code,Degree,Student Name,Mid,Quiz 1,Quiz 2,Best of Quizzes,Assignment 1,Assignment 2,Best of Assignments,Total Sessional (50),Final (50),Total (100),Grade
0,022-14-19987,BS(CS),Abdul Basit,28,8.0,3.0,8,7.0,9.0,9,45,25.0,70,B
1,022-14-110233,BS(CS),Adeel Ahmed,17,NaN,5.0,5,8.0,10.0,10,32,18.0,50,F
2,022-14-110585,BS(CS),Afrah Zareen,18,5.0,2.0,5,8.0,10.0,10,33,30.0,63,C
3,022-14-19718,BS(CS),Ahmed Ali Raza,14,7.0,2.0,7,NaN,2.0,2,23,23.0,46,F
4,022-14-110648,BS(CS),Ahsan Ali Vohra,27,7.0,6.0,7,7.0,9.0,9,43,34.0,77,B
5,022-14-110232,BS(CS),Ameer Hamza,25,9.0,6.0,9,8.0,10.0,10,44,27.0,71,B
6,022-14-110588,BS(CS),Anas Ali Khan,28,5.0,6.0,6,8.0,10.0,10,44,30.0,74,B
7,022-14-110388,BS(CS),Aneebullah Niazi,26,9.0,6.0,9,8.0,10.0,10,45,40.0,85,A
8,022-14-110601,BS(CS),Areesha Sohail,19,9.0,4.0,9,7.0,9.0,9,37,24.0,61,C
9,022-14-110599,BS(CS),Arsalan,28,8.0,6.0,8,8.0,NaN,8,44,40.0,84,A
10,022-14-110214,BS(CS),Fatima Haider Warsi,30,8.0,7.0,8,8.0,NaN,8,46,45.0,91,A
11,022-14-110591,BS(CS),Habib Ullah,28,8.0,5.0,8,5.0,NaN,5,41,35.0,76,B
12,022-15-110994,BS(CS),Hafiza Tooba Akbani,23,7.0,5.0,7,8.0,10.0,10,40,33.0,73,B
13,022-14-110600,BS(CS),Hamza Abdul Jabbar,24,8.0,4.0,8,8.0,10.0,10,42,25.0,67,C
14,022-14-110389,BS(CS),Hareem Afshan,21,7.0,4.0,7,6.0,8.0,8,36,29.0,65,C
15,022-14-19916,BS(CS),Haseeb Sajid,18,NaN,NaN,0,NaN,NaN,0,18,NaN,18,F
16,022-14-110596,BS(CS),Hassam Ahmed,23,5.0,5.0,5,7.0,9.0,9,37,35.0,72,B
17,022-14-110396,BS(CS),Khalid Anwer,20,8.0,5.0,8,9.0,11.0,11,39,31.0,70,B
18,022-14-110223,BS(CS),Madiha Jabeen,16,5.0,2.0,5,8.0,10.0,10,31,29.0,60,C
19,022-14-110222,BS(CS),Mohammad Hunain,27,9.0,6.0,9,8.0,10.0,10,46,45.0,91,A
20,022-14-110412,BS(CS),Muhammad Aamir,24,7.0,6.0,7,7.0,9.0,9,40,31.0,71,B
21,022-14-110593,BS(CS),Muhammad Abdul Rehman Siddiqui,20,9.0,6.0,9,9.0,11.0,11,40,20.0,60,C
22,022-14-110398,BS(CS),Muhammad Abdullah,20,7.0,6.0,7,7.0,NaN,7,34,23.0,57,F
23,022-14-19983,BS(CS),Muhammad Ali Iqbal,26,5.0,NaN,5,8.0,10.0,10,41,21.0,62,C
24,022-14-110215,BS(CS),Muhammad Bilal,28,5.0,4.0,5,9.0,11.0,11,44,33.0,77,B
25,022-14-110105,BS(CS),Muhammad Faraz,26,9.0,6.0,9,8.0,10.0,10,45,41.0,86,A
26,022-14-110370,BS(CS),Muhammad Ghazali Faridi,27,6.0,NaN,6,6.0,8.0,8,41,24.0,65,C
27,022-14-110452,BS(CS),Muhammad Osama Khan,27,8.0,6.0,8,8.0,10.0,10,45,26.0,71,B
28,022-14-110387,BS(CS),Muhammad Saqib Intizar,22,6.0,6.0,6,9.0,11.0,11,39,18.0,57,F
29,022-14-110217,BS(CS),Muhammad Shahroz Khurshid,17,7.0,1.0,7,6.0,NaN,6,30,9.0,39,F
30,022-14-110401,BS(CS),Muhammad Shozab,23,8.0,6.0,8,9.0,NaN,9,40,32.0,72,B
31,022-14-110231,BS(CS),Muhammad Taha Hasnain,27,7.0,5.0,7,10.0,NaN,10,44,29.0,73,B
32,022-14-110035,BS(CS),Muhammad Wajahat Khan,9,NaN,2.0,2,8.0,10.0,10,21,8.0,29,F
33,022-14-19919,BS(CS),Muhammad Younus Baig,20,4.0,2.0,4,8.0,10.0,10,34,17.0,51,F
34,022-14-110413,BS(CS),Nazeer Bin Zafar,25,9.0,6.0,9,8.0,10.0,10,44,42.0,86,A
35,022-14-19923,BS(CS),Rabi Ahmed,20,8.0,5.0,8,NaN,10.0,10,38,28.0,66,C
36,022-14-110582,BS(CS),Rida Nasim,25,9.0,5.0,9,9.0,NaN,9,43,27.0,70,B
37,022-14-110230,BS(CS),Sadaf Nosheen,27,9.0,5.0,9,9.0,NaN,9,45,30.0,75,B
38,022-14-110229,BS(CS),Sadaquat Rafique,9,6.0,6.0,6,5.0,7.0,7,22,17.0,39,F
39,022-14-110107,BS(CS),Sania Iqbal,28,4.0,4.0,4,9.0,11.0,11,43,25.0,68,C
40,022-14-110584,BS(CS),Sharif Taqi,27,9.0,6.0,9,8.0,10.0,10,46,35.0,81,A
41,022-14-110225,BS(CS),Shariqa Ahmad,20,7.0,6.0,7,8.0,10.0,10,37,20.0,57,F
42,022-14-110587,BS(CS),Sumbul Rehman,28,5.0,6.0,6,8.0,10.0,10,44,23.0,67,C
43,022-14-110451,BS(CS),Syed Faizan Uddin,28,9.0,4.0,9,6.0,8.0,8,45,34.0,79,B
44,022-14-110589,BS(CS),Syed Sohaib,25,7.0,5.0,7,9.0,NaN,9,41,22.0,63,C
45,022-14-110400,BS(CS),Syeda Sabika Raza,27,9.0,6.0,9,9.0,NaN,9,45,35.0,80,A
46,022-14-19911,BS(CS),Usman Khan,25,8.0,5.0,8,8.0,10.0,10,43,22.0,65,C
47,022-14-110219,BS(CS),Waqar Ahmed,11,9.0,5.0,9,5.0,7.0,7,27,19.0,46,F

### 4. What are the columns in the dataframe?

In [17]:
print(UNV.columns)

Index(['Student Code', 'Degree', 'Student Name', 'Mid', 'Quiz 1', 'Quiz 2',
       'Best of Quizzes', 'Assignment 1', 'Assignment 2',
       'Best of Assignments', 'Total Sessional (50)', 'Final (50)',
       'Total (100)', 'Grade'],
      dtype='object')

In [19]:
print(UNV.shape)

(48, 14)

In [20]:
print(UNV.info)

<bound method DataFrame.info of      Student Code  Degree                    Student Name  Mid  Quiz 1  \
0    022-14-19987  BS(CS)                     Abdul Basit   28     8.0
1   022-14-110233  BS(CS)                     Adeel Ahmed   17     NaN
2   022-14-110585  BS(CS)                    Afrah Zareen   18     5.0
3    022-14-19718  BS(CS)                  Ahmed Ali Raza   14     7.0
4   022-14-110648  BS(CS)                 Ahsan Ali Vohra   27     7.0
5   022-14-110232  BS(CS)                     Ameer Hamza   25     9.0
6   022-14-110588  BS(CS)                   Anas Ali Khan   28     5.0
7   022-14-110388  BS(CS)                Aneebullah Niazi   26     9.0
8   022-14-110601  BS(CS)                  Areesha Sohail   19     9.0
9   022-14-110599  BS(CS)                         Arsalan   28     8.0
10  022-14-110214  BS(CS)             Fatima Haider Warsi   30     8.0
11  022-14-110591  BS(CS)                     Habib Ullah   28     8.0
12  022-15-110994  BS(CS)             Hafiza Tooba Akbani   23     7.0
13  022-14-110600  BS(CS)              Hamza Abdul Jabbar   24     8.0
14  022-14-110389  BS(CS)                   Hareem Afshan   21     7.0
15   022-14-19916  BS(CS)                    Haseeb Sajid   18     NaN
16  022-14-110596  BS(CS)                    Hassam Ahmed   23     5.0
17  022-14-110396  BS(CS)                    Khalid Anwer   20     8.0
18  022-14-110223  BS(CS)                   Madiha Jabeen   16     5.0
19  022-14-110222  BS(CS)                 Mohammad Hunain   27     9.0
20  022-14-110412  BS(CS)                  Muhammad Aamir   24     7.0
21  022-14-110593  BS(CS)  Muhammad Abdul Rehman Siddiqui   20     9.0
22  022-14-110398  BS(CS)               Muhammad Abdullah   20     7.0
23   022-14-19983  BS(CS)              Muhammad Ali Iqbal   26     5.0
24  022-14-110215  BS(CS)                  Muhammad Bilal   28     5.0
25  022-14-110105  BS(CS)                  Muhammad Faraz   26     9.0
26  022-14-110370  BS(CS)         Muhammad Ghazali Faridi   27     6.0
27  022-14-110452  BS(CS)             Muhammad Osama Khan   27     8.0
28  022-14-110387  BS(CS)          Muhammad Saqib Intizar   22     6.0
29  022-14-110217  BS(CS)       Muhammad Shahroz Khurshid   17     7.0
30  022-14-110401  BS(CS)                 Muhammad Shozab   23     8.0
31  022-14-110231  BS(CS)           Muhammad Taha Hasnain   27     7.0
32  022-14-110035  BS(CS)           Muhammad Wajahat Khan    9     NaN
33   022-14-19919  BS(CS)            Muhammad Younus Baig   20     4.0
34  022-14-110413  BS(CS)                Nazeer Bin Zafar   25     9.0
35   022-14-19923  BS(CS)                      Rabi Ahmed   20     8.0
36  022-14-110582  BS(CS)                      Rida Nasim   25     9.0
37  022-14-110230  BS(CS)                   Sadaf Nosheen   27     9.0
38  022-14-110229  BS(CS)                Sadaquat Rafique    9     6.0
39  022-14-110107  BS(CS)                     Sania Iqbal   28     4.0
40  022-14-110584  BS(CS)                     Sharif Taqi   27     9.0
41  022-14-110225  BS(CS)                   Shariqa Ahmad   20     7.0
42  022-14-110587  BS(CS)                   Sumbul Rehman   28     5.0
43  022-14-110451  BS(CS)               Syed Faizan Uddin   28     9.0
44  022-14-110589  BS(CS)                     Syed Sohaib   25     7.0
45  022-14-110400  BS(CS)               Syeda Sabika Raza   27     9.0
46   022-14-19911  BS(CS)                      Usman Khan   25     8.0
47  022-14-110219  BS(CS)                     Waqar Ahmed   11     9.0

    Quiz 2  Best of Quizzes  Assignment 1  Assignment 2  Best of Assignments  \
0      3.0                8           7.0           9.0                    9
1      5.0                5           8.0          10.0                   10
2      2.0                5           8.0          10.0                   10
3      2.0                7           NaN           2.0                    2
4      6.0                7           7.0           9.0                    9
5      6.0                9           8.0          10.0                   10
6      6.0                6           8.0          10.0                   10
7      6.0                9           8.0          10.0                   10
8      4.0                9           7.0           9.0                    9
9      6.0                8           8.0           NaN                    8
10     7.0                8           8.0           NaN                    8
11     5.0                8           5.0           NaN                    5
12     5.0                7           8.0          10.0                   10
13     4.0                8           8.0          10.0                   10
14     4.0                7           6.0           8.0                    8
15     NaN                0           NaN           NaN                    0
16     5.0                5           7.0           9.0                    9
17     5.0                8           9.0          11.0                   11
18     2.0                5           8.0          10.0                   10
19     6.0                9           8.0          10.0                   10
20     6.0                7           7.0           9.0                    9
21     6.0                9           9.0          11.0                   11
22     6.0                7           7.0           NaN                    7
23     NaN                5           8.0          10.0                   10
24     4.0                5           9.0          11.0                   11
25     6.0                9           8.0          10.0                   10
26     NaN                6           6.0           8.0                    8
27     6.0                8           8.0          10.0                   10
28     6.0                6           9.0          11.0                   11
29     1.0                7           6.0           NaN                    6
30     6.0                8           9.0           NaN                    9
31     5.0                7          10.0           NaN                   10
32     2.0                2           8.0          10.0                   10
33     2.0                4           8.0          10.0                   10
34     6.0                9           8.0          10.0                   10
35     5.0                8           NaN          10.0                   10
36     5.0                9           9.0           NaN                    9
37     5.0                9           9.0           NaN                    9
38     6.0                6           5.0           7.0                    7
39     4.0                4           9.0          11.0                   11
40     6.0                9           8.0          10.0                   10
41     6.0                7           8.0          10.0                   10
42     6.0                6           8.0          10.0                   10
43     4.0                9           6.0           8.0                    8
44     5.0                7           9.0           NaN                    9
45     6.0                9           9.0           NaN                    9
46     5.0                8           8.0          10.0                   10
47     5.0                9           5.0           7.0                    7

    Total Sessional (50)  Final (50)  Total (100) Grade
0                     45        25.0           70     B
1                     32        18.0           50     F
2                     33        30.0           63     C
3                     23        23.0           46     F
4                     43        34.0           77     B
5                     44        27.0           71     B
6                     44        30.0           74     B
7                     45        40.0           85     A
8                     37        24.0           61     C
9                     44        40.0           84     A
10                    46        45.0           91     A
11                    41        35.0           76     B
12                    40        33.0           73     B
13                    42        25.0           67     C
14                    36        29.0           65     C
15                    18         NaN           18     F
16                    37        35.0           72     B
17                    39        31.0           70     B
18                    31        29.0           60     C
19                    46        45.0           91     A
20                    40        31.0           71     B
21                    40        20.0           60     C
22                    34        23.0           57     F
23                    41        21.0           62     C
24                    44        33.0           77     B
25                    45        41.0           86     A
26                    41        24.0           65     C
27                    45        26.0           71     B
28                    39        18.0           57     F
29                    30         9.0           39     F
30                    40        32.0           72     B
31                    44        29.0           73     B
32                    21         8.0           29     F
33                    34        17.0           51     F
34                    44        42.0           86     A
35                    38        28.0           66     C
36                    43        27.0           70     B
37                    45        30.0           75     B
38                    22        17.0           39     F
39                    43        25.0           68     C
40                    46        35.0           81     A
41                    37        20.0           57     F
42                    44        23.0           67     C
43                    45        34.0           79     B
44                    41        22.0           63     C
45                    45        35.0           80     A
46                    43        22.0           65     C
47                    27        19.0           46     F  >

In [21]:
print(UNV.index)

RangeIndex(start=0, stop=48, step=1)

In [22]:
print(UNV.count)

<bound method DataFrame.count of      Student Code  Degree                    Student Name  Mid  Quiz 1  \
0    022-14-19987  BS(CS)                     Abdul Basit   28     8.0
1   022-14-110233  BS(CS)                     Adeel Ahmed   17     NaN
2   022-14-110585  BS(CS)                    Afrah Zareen   18     5.0
3    022-14-19718  BS(CS)                  Ahmed Ali Raza   14     7.0
4   022-14-110648  BS(CS)                 Ahsan Ali Vohra   27     7.0
5   022-14-110232  BS(CS)                     Ameer Hamza   25     9.0
6   022-14-110588  BS(CS)                   Anas Ali Khan   28     5.0
7   022-14-110388  BS(CS)                Aneebullah Niazi   26     9.0
8   022-14-110601  BS(CS)                  Areesha Sohail   19     9.0
9   022-14-110599  BS(CS)                         Arsalan   28     8.0
10  022-14-110214  BS(CS)             Fatima Haider Warsi   30     8.0
11  022-14-110591  BS(CS)                     Habib Ullah   28     8.0
12  022-15-110994  BS(CS)             Hafiza Tooba Akbani   23     7.0
13  022-14-110600  BS(CS)              Hamza Abdul Jabbar   24     8.0
14  022-14-110389  BS(CS)                   Hareem Afshan   21     7.0
15   022-14-19916  BS(CS)                    Haseeb Sajid   18     NaN
16  022-14-110596  BS(CS)                    Hassam Ahmed   23     5.0
17  022-14-110396  BS(CS)                    Khalid Anwer   20     8.0
18  022-14-110223  BS(CS)                   Madiha Jabeen   16     5.0
19  022-14-110222  BS(CS)                 Mohammad Hunain   27     9.0
20  022-14-110412  BS(CS)                  Muhammad Aamir   24     7.0
21  022-14-110593  BS(CS)  Muhammad Abdul Rehman Siddiqui   20     9.0
22  022-14-110398  BS(CS)               Muhammad Abdullah   20     7.0
23   022-14-19983  BS(CS)              Muhammad Ali Iqbal   26     5.0
24  022-14-110215  BS(CS)                  Muhammad Bilal   28     5.0
25  022-14-110105  BS(CS)                  Muhammad Faraz   26     9.0
26  022-14-110370  BS(CS)         Muhammad Ghazali Faridi   27     6.0
27  022-14-110452  BS(CS)             Muhammad Osama Khan   27     8.0
28  022-14-110387  BS(CS)          Muhammad Saqib Intizar   22     6.0
29  022-14-110217  BS(CS)       Muhammad Shahroz Khurshid   17     7.0
30  022-14-110401  BS(CS)                 Muhammad Shozab   23     8.0
31  022-14-110231  BS(CS)           Muhammad Taha Hasnain   27     7.0
32  022-14-110035  BS(CS)           Muhammad Wajahat Khan    9     NaN
33   022-14-19919  BS(CS)            Muhammad Younus Baig   20     4.0
34  022-14-110413  BS(CS)                Nazeer Bin Zafar   25     9.0
35   022-14-19923  BS(CS)                      Rabi Ahmed   20     8.0
36  022-14-110582  BS(CS)                      Rida Nasim   25     9.0
37  022-14-110230  BS(CS)                   Sadaf Nosheen   27     9.0
38  022-14-110229  BS(CS)                Sadaquat Rafique    9     6.0
39  022-14-110107  BS(CS)                     Sania Iqbal   28     4.0
40  022-14-110584  BS(CS)                     Sharif Taqi   27     9.0
41  022-14-110225  BS(CS)                   Shariqa Ahmad   20     7.0
42  022-14-110587  BS(CS)                   Sumbul Rehman   28     5.0
43  022-14-110451  BS(CS)               Syed Faizan Uddin   28     9.0
44  022-14-110589  BS(CS)                     Syed Sohaib   25     7.0
45  022-14-110400  BS(CS)               Syeda Sabika Raza   27     9.0
46   022-14-19911  BS(CS)                      Usman Khan   25     8.0
47  022-14-110219  BS(CS)                     Waqar Ahmed   11     9.0

    Quiz 2  Best of Quizzes  Assignment 1  Assignment 2  Best of Assignments  \
0      3.0                8           7.0           9.0                    9
1      5.0                5           8.0          10.0                   10
2      2.0                5           8.0          10.0                   10
3      2.0                7           NaN           2.0                    2
4      6.0                7           7.0           9.0                    9
5      6.0                9           8.0          10.0                   10
6      6.0                6           8.0          10.0                   10
7      6.0                9           8.0          10.0                   10
8      4.0                9           7.0           9.0                    9
9      6.0                8           8.0           NaN                    8
10     7.0                8           8.0           NaN                    8
11     5.0                8           5.0           NaN                    5
12     5.0                7           8.0          10.0                   10
13     4.0                8           8.0          10.0                   10
14     4.0                7           6.0           8.0                    8
15     NaN                0           NaN           NaN                    0
16     5.0                5           7.0           9.0                    9
17     5.0                8           9.0          11.0                   11
18     2.0                5           8.0          10.0                   10
19     6.0                9           8.0          10.0                   10
20     6.0                7           7.0           9.0                    9
21     6.0                9           9.0          11.0                   11
22     6.0                7           7.0           NaN                    7
23     NaN                5           8.0          10.0                   10
24     4.0                5           9.0          11.0                   11
25     6.0                9           8.0          10.0                   10
26     NaN                6           6.0           8.0                    8
27     6.0                8           8.0          10.0                   10
28     6.0                6           9.0          11.0                   11
29     1.0                7           6.0           NaN                    6
30     6.0                8           9.0           NaN                    9
31     5.0                7          10.0           NaN                   10
32     2.0                2           8.0          10.0                   10
33     2.0                4           8.0          10.0                   10
34     6.0                9           8.0          10.0                   10
35     5.0                8           NaN          10.0                   10
36     5.0                9           9.0           NaN                    9
37     5.0                9           9.0           NaN                    9
38     6.0                6           5.0           7.0                    7
39     4.0                4           9.0          11.0                   11
40     6.0                9           8.0          10.0                   10
41     6.0                7           8.0          10.0                   10
42     6.0                6           8.0          10.0                   10
43     4.0                9           6.0           8.0                    8
44     5.0                7           9.0           NaN                    9
45     6.0                9           9.0           NaN                    9
46     5.0                8           8.0          10.0                   10
47     5.0                9           5.0           7.0                    7

    Total Sessional (50)  Final (50)  Total (100) Grade
0                     45        25.0           70     B
1                     32        18.0           50     F
2                     33        30.0           63     C
3                     23        23.0           46     F
4                     43        34.0           77     B
5                     44        27.0           71     B
6                     44        30.0           74     B
7                     45        40.0           85     A
8                     37        24.0           61     C
9                     44        40.0           84     A
10                    46        45.0           91     A
11                    41        35.0           76     B
12                    40        33.0           73     B
13                    42        25.0           67     C
14                    36        29.0           65     C
15                    18         NaN           18     F
16                    37        35.0           72     B
17                    39        31.0           70     B
18                    31        29.0           60     C
19                    46        45.0           91     A
20                    40        31.0           71     B
21                    40        20.0           60     C
22                    34        23.0           57     F
23                    41        21.0           62     C
24                    44        33.0           77     B
25                    45        41.0           86     A
26                    41        24.0           65     C
27                    45        26.0           71     B
28                    39        18.0           57     F
29                    30         9.0           39     F
30                    40        32.0           72     B
31                    44        29.0           73     B
32                    21         8.0           29     F
33                    34        17.0           51     F
34                    44        42.0           86     A
35                    38        28.0           66     C
36                    43        27.0           70     B
37                    45        30.0           75     B
38                    22        17.0           39     F
39                    43        25.0           68     C
40                    46        35.0           81     A
41                    37        20.0           57     F
42                    44        23.0           67     C
43                    45        34.0           79     B
44                    41        22.0           63     C
45                    45        35.0           80     A
46                    43        22.0           65     C
47                    27        19.0           46     F  >

### 5. Sort the data based on Marks obtained. Fill all the 'na' cells with 0

In [23]:
print(UNV.sort_index)

<bound method DataFrame.sort_index of      Student Code  Degree                    Student Name  Mid  Quiz 1  \
0    022-14-19987  BS(CS)                     Abdul Basit   28     8.0
1   022-14-110233  BS(CS)                     Adeel Ahmed   17     NaN
2   022-14-110585  BS(CS)                    Afrah Zareen   18     5.0
3    022-14-19718  BS(CS)                  Ahmed Ali Raza   14     7.0
4   022-14-110648  BS(CS)                 Ahsan Ali Vohra   27     7.0
5   022-14-110232  BS(CS)                     Ameer Hamza   25     9.0
6   022-14-110588  BS(CS)                   Anas Ali Khan   28     5.0
7   022-14-110388  BS(CS)                Aneebullah Niazi   26     9.0
8   022-14-110601  BS(CS)                  Areesha Sohail   19     9.0
9   022-14-110599  BS(CS)                         Arsalan   28     8.0
10  022-14-110214  BS(CS)             Fatima Haider Warsi   30     8.0
11  022-14-110591  BS(CS)                     Habib Ullah   28     8.0
12  022-15-110994  BS(CS)             Hafiza Tooba Akbani   23     7.0
13  022-14-110600  BS(CS)              Hamza Abdul Jabbar   24     8.0
14  022-14-110389  BS(CS)                   Hareem Afshan   21     7.0
15   022-14-19916  BS(CS)                    Haseeb Sajid   18     NaN
16  022-14-110596  BS(CS)                    Hassam Ahmed   23     5.0
17  022-14-110396  BS(CS)                    Khalid Anwer   20     8.0
18  022-14-110223  BS(CS)                   Madiha Jabeen   16     5.0
19  022-14-110222  BS(CS)                 Mohammad Hunain   27     9.0
20  022-14-110412  BS(CS)                  Muhammad Aamir   24     7.0
21  022-14-110593  BS(CS)  Muhammad Abdul Rehman Siddiqui   20     9.0
22  022-14-110398  BS(CS)               Muhammad Abdullah   20     7.0
23   022-14-19983  BS(CS)              Muhammad Ali Iqbal   26     5.0
24  022-14-110215  BS(CS)                  Muhammad Bilal   28     5.0
25  022-14-110105  BS(CS)                  Muhammad Faraz   26     9.0
26  022-14-110370  BS(CS)         Muhammad Ghazali Faridi   27     6.0
27  022-14-110452  BS(CS)             Muhammad Osama Khan   27     8.0
28  022-14-110387  BS(CS)          Muhammad Saqib Intizar   22     6.0
29  022-14-110217  BS(CS)       Muhammad Shahroz Khurshid   17     7.0
30  022-14-110401  BS(CS)                 Muhammad Shozab   23     8.0
31  022-14-110231  BS(CS)           Muhammad Taha Hasnain   27     7.0
32  022-14-110035  BS(CS)           Muhammad Wajahat Khan    9     NaN
33   022-14-19919  BS(CS)            Muhammad Younus Baig   20     4.0
34  022-14-110413  BS(CS)                Nazeer Bin Zafar   25     9.0
35   022-14-19923  BS(CS)                      Rabi Ahmed   20     8.0
36  022-14-110582  BS(CS)                      Rida Nasim   25     9.0
37  022-14-110230  BS(CS)                   Sadaf Nosheen   27     9.0
38  022-14-110229  BS(CS)                Sadaquat Rafique    9     6.0
39  022-14-110107  BS(CS)                     Sania Iqbal   28     4.0
40  022-14-110584  BS(CS)                     Sharif Taqi   27     9.0
41  022-14-110225  BS(CS)                   Shariqa Ahmad   20     7.0
42  022-14-110587  BS(CS)                   Sumbul Rehman   28     5.0
43  022-14-110451  BS(CS)               Syed Faizan Uddin   28     9.0
44  022-14-110589  BS(CS)                     Syed Sohaib   25     7.0
45  022-14-110400  BS(CS)               Syeda Sabika Raza   27     9.0
46   022-14-19911  BS(CS)                      Usman Khan   25     8.0
47  022-14-110219  BS(CS)                     Waqar Ahmed   11     9.0

    Quiz 2  Best of Quizzes  Assignment 1  Assignment 2  Best of Assignments  \
0      3.0                8           7.0           9.0                    9
1      5.0                5           8.0          10.0                   10
2      2.0                5           8.0          10.0                   10
3      2.0                7           NaN           2.0                    2
4      6.0                7           7.0           9.0                    9
5      6.0                9           8.0          10.0                   10
6      6.0                6           8.0          10.0                   10
7      6.0                9           8.0          10.0                   10
8      4.0                9           7.0           9.0                    9
9      6.0                8           8.0           NaN                    8
10     7.0                8           8.0           NaN                    8
11     5.0                8           5.0           NaN                    5
12     5.0                7           8.0          10.0                   10
13     4.0                8           8.0          10.0                   10
14     4.0                7           6.0           8.0                    8
15     NaN                0           NaN           NaN                    0
16     5.0                5           7.0           9.0                    9
17     5.0                8           9.0          11.0                   11
18     2.0                5           8.0          10.0                   10
19     6.0                9           8.0          10.0                   10
20     6.0                7           7.0           9.0                    9
21     6.0                9           9.0          11.0                   11
22     6.0                7           7.0           NaN                    7
23     NaN                5           8.0          10.0                   10
24     4.0                5           9.0          11.0                   11
25     6.0                9           8.0          10.0                   10
26     NaN                6           6.0           8.0                    8
27     6.0                8           8.0          10.0                   10
28     6.0                6           9.0          11.0                   11
29     1.0                7           6.0           NaN                    6
30     6.0                8           9.0           NaN                    9
31     5.0                7          10.0           NaN                   10
32     2.0                2           8.0          10.0                   10
33     2.0                4           8.0          10.0                   10
34     6.0                9           8.0          10.0                   10
35     5.0                8           NaN          10.0                   10
36     5.0                9           9.0           NaN                    9
37     5.0                9           9.0           NaN                    9
38     6.0                6           5.0           7.0                    7
39     4.0                4           9.0          11.0                   11
40     6.0                9           8.0          10.0                   10
41     6.0                7           8.0          10.0                   10
42     6.0                6           8.0          10.0                   10
43     4.0                9           6.0           8.0                    8
44     5.0                7           9.0           NaN                    9
45     6.0                9           9.0           NaN                    9
46     5.0                8           8.0          10.0                   10
47     5.0                9           5.0           7.0                    7

    Total Sessional (50)  Final (50)  Total (100) Grade
0                     45        25.0           70     B
1                     32        18.0           50     F
2                     33        30.0           63     C
3                     23        23.0           46     F
4                     43        34.0           77     B
5                     44        27.0           71     B
6                     44        30.0           74     B
7                     45        40.0           85     A
8                     37        24.0           61     C
9                     44        40.0           84     A
10                    46        45.0           91     A
11                    41        35.0           76     B
12                    40        33.0           73     B
13                    42        25.0           67     C
14                    36        29.0           65     C
15                    18         NaN           18     F
16                    37        35.0           72     B
17                    39        31.0           70     B
18                    31        29.0           60     C
19                    46        45.0           91     A
20                    40        31.0           71     B
21                    40        20.0           60     C
22                    34        23.0           57     F
23                    41        21.0           62     C
24                    44        33.0           77     B
25                    45        41.0           86     A
26                    41        24.0           65     C
27                    45        26.0           71     B
28                    39        18.0           57     F
29                    30         9.0           39     F
30                    40        32.0           72     B
31                    44        29.0           73     B
32                    21         8.0           29     F
33                    34        17.0           51     F
34                    44        42.0           86     A
35                    38        28.0           66     C
36                    43        27.0           70     B
37                    45        30.0           75     B
38                    22        17.0           39     F
39                    43        25.0           68     C
40                    46        35.0           81     A
41                    37        20.0           57     F
42                    44        23.0           67     C
43                    45        34.0           79     B
44                    41        22.0           63     C
45                    45        35.0           80     A
46                    43        22.0           65     C
47                    27        19.0           46     F  >

In [24]:
print(UNV.sort_values(by='Grade'))

     Student Code  Degree                    Student Name  Mid  Quiz 1  \
40  022-14-110584  BS(CS)                     Sharif Taqi   27     9.0
45  022-14-110400  BS(CS)               Syeda Sabika Raza   27     9.0
25  022-14-110105  BS(CS)                  Muhammad Faraz   26     9.0
34  022-14-110413  BS(CS)                Nazeer Bin Zafar   25     9.0
7   022-14-110388  BS(CS)                Aneebullah Niazi   26     9.0
19  022-14-110222  BS(CS)                 Mohammad Hunain   27     9.0
9   022-14-110599  BS(CS)                         Arsalan   28     8.0
10  022-14-110214  BS(CS)             Fatima Haider Warsi   30     8.0
24  022-14-110215  BS(CS)                  Muhammad Bilal   28     5.0
31  022-14-110231  BS(CS)           Muhammad Taha Hasnain   27     7.0
20  022-14-110412  BS(CS)                  Muhammad Aamir   24     7.0
36  022-14-110582  BS(CS)                      Rida Nasim   25     9.0
17  022-14-110396  BS(CS)                    Khalid Anwer   20     8.0
16  022-14-110596  BS(CS)                    Hassam Ahmed   23     5.0
37  022-14-110230  BS(CS)                   Sadaf Nosheen   27     9.0
0    022-14-19987  BS(CS)                     Abdul Basit   28     8.0
30  022-14-110401  BS(CS)                 Muhammad Shozab   23     8.0
12  022-15-110994  BS(CS)             Hafiza Tooba Akbani   23     7.0
11  022-14-110591  BS(CS)                     Habib Ullah   28     8.0
6   022-14-110588  BS(CS)                   Anas Ali Khan   28     5.0
5   022-14-110232  BS(CS)                     Ameer Hamza   25     9.0
4   022-14-110648  BS(CS)                 Ahsan Ali Vohra   27     7.0
43  022-14-110451  BS(CS)               Syed Faizan Uddin   28     9.0
27  022-14-110452  BS(CS)             Muhammad Osama Khan   27     8.0
42  022-14-110587  BS(CS)                   Sumbul Rehman   28     5.0
35   022-14-19923  BS(CS)                      Rabi Ahmed   20     8.0
44  022-14-110589  BS(CS)                     Syed Sohaib   25     7.0
39  022-14-110107  BS(CS)                     Sania Iqbal   28     4.0
23   022-14-19983  BS(CS)              Muhammad Ali Iqbal   26     5.0
26  022-14-110370  BS(CS)         Muhammad Ghazali Faridi   27     6.0
46   022-14-19911  BS(CS)                      Usman Khan   25     8.0
2   022-14-110585  BS(CS)                    Afrah Zareen   18     5.0
21  022-14-110593  BS(CS)  Muhammad Abdul Rehman Siddiqui   20     9.0
18  022-14-110223  BS(CS)                   Madiha Jabeen   16     5.0
8   022-14-110601  BS(CS)                  Areesha Sohail   19     9.0
14  022-14-110389  BS(CS)                   Hareem Afshan   21     7.0
13  022-14-110600  BS(CS)              Hamza Abdul Jabbar   24     8.0
29  022-14-110217  BS(CS)       Muhammad Shahroz Khurshid   17     7.0
1   022-14-110233  BS(CS)                     Adeel Ahmed   17     NaN
3    022-14-19718  BS(CS)                  Ahmed Ali Raza   14     7.0
41  022-14-110225  BS(CS)                   Shariqa Ahmad   20     7.0
38  022-14-110229  BS(CS)                Sadaquat Rafique    9     6.0
15   022-14-19916  BS(CS)                    Haseeb Sajid   18     NaN
22  022-14-110398  BS(CS)               Muhammad Abdullah   20     7.0
33   022-14-19919  BS(CS)            Muhammad Younus Baig   20     4.0
32  022-14-110035  BS(CS)           Muhammad Wajahat Khan    9     NaN
28  022-14-110387  BS(CS)          Muhammad Saqib Intizar   22     6.0
47  022-14-110219  BS(CS)                     Waqar Ahmed   11     9.0

    Quiz 2  Best of Quizzes  Assignment 1  Assignment 2  Best of Assignments  \
40     6.0                9           8.0          10.0                   10
45     6.0                9           9.0           NaN                    9
25     6.0                9           8.0          10.0                   10
34     6.0                9           8.0          10.0                   10
7      6.0                9           8.0          10.0                   10
19     6.0                9           8.0          10.0                   10
9      6.0                8           8.0           NaN                    8
10     7.0                8           8.0           NaN                    8
24     4.0                5           9.0          11.0                   11
31     5.0                7          10.0           NaN                   10
20     6.0                7           7.0           9.0                    9
36     5.0                9           9.0           NaN                    9
17     5.0                8           9.0          11.0                   11
16     5.0                5           7.0           9.0                    9
37     5.0                9           9.0           NaN                    9
0      3.0                8           7.0           9.0                    9
30     6.0                8           9.0           NaN                    9
12     5.0                7           8.0          10.0                   10
11     5.0                8           5.0           NaN                    5
6      6.0                6           8.0          10.0                   10
5      6.0                9           8.0          10.0                   10
4      6.0                7           7.0           9.0                    9
43     4.0                9           6.0           8.0                    8
27     6.0                8           8.0          10.0                   10
42     6.0                6           8.0          10.0                   10
35     5.0                8           NaN          10.0                   10
44     5.0                7           9.0           NaN                    9
39     4.0                4           9.0          11.0                   11
23     NaN                5           8.0          10.0                   10
26     NaN                6           6.0           8.0                    8
46     5.0                8           8.0          10.0                   10
2      2.0                5           8.0          10.0                   10
21     6.0                9           9.0          11.0                   11
18     2.0                5           8.0          10.0                   10
8      4.0                9           7.0           9.0                    9
14     4.0                7           6.0           8.0                    8
13     4.0                8           8.0          10.0                   10
29     1.0                7           6.0           NaN                    6
1      5.0                5           8.0          10.0                   10
3      2.0                7           NaN           2.0                    2
41     6.0                7           8.0          10.0                   10
38     6.0                6           5.0           7.0                    7
15     NaN                0           NaN           NaN                    0
22     6.0                7           7.0           NaN                    7
33     2.0                4           8.0          10.0                   10
32     2.0                2           8.0          10.0                   10
28     6.0                6           9.0          11.0                   11
47     5.0                9           5.0           7.0                    7

    Total Sessional (50)  Final (50)  Total (100) Grade
40                    46        35.0           81     A
45                    45        35.0           80     A
25                    45        41.0           86     A
34                    44        42.0           86     A
7                     45        40.0           85     A
19                    46        45.0           91     A
9                     44        40.0           84     A
10                    46        45.0           91     A
24                    44        33.0           77     B
31                    44        29.0           73     B
20                    40        31.0           71     B
36                    43        27.0           70     B
17                    39        31.0           70     B
16                    37        35.0           72     B
37                    45        30.0           75     B
0                     45        25.0           70     B
30                    40        32.0           72     B
12                    40        33.0           73     B
11                    41        35.0           76     B
6                     44        30.0           74     B
5                     44        27.0           71     B
4                     43        34.0           77     B
43                    45        34.0           79     B
27                    45        26.0           71     B
42                    44        23.0           67     C
35                    38        28.0           66     C
44                    41        22.0           63     C
39                    43        25.0           68     C
23                    41        21.0           62     C
26                    41        24.0           65     C
46                    43        22.0           65     C
2                     33        30.0           63     C
21                    40        20.0           60     C
18                    31        29.0           60     C
8                     37        24.0           61     C
14                    36        29.0           65     C
13                    42        25.0           67     C
29                    30         9.0           39     F
1                     32        18.0           50     F
3                     23        23.0           46     F
41                    37        20.0           57     F
38                    22        17.0           39     F
15                    18         NaN           18     F
22                    34        23.0           57     F
33                    34        17.0           51     F
32                    21         8.0           29     F
28                    39        18.0           57     F
47                    27        19.0           46     F

In [25]:
print(UNV.rank())

    Student Code  Degree  Student Name   Mid  Quiz 1  Quiz 2  Best of Quizzes  \
0           47.0    24.5           1.0  43.5    27.5     7.0             30.5
1           15.0    24.5           2.0   6.5     NaN    19.5              7.5
2           30.0    24.5           3.0   8.5     6.0     4.0              7.5
3           41.0    24.5           4.0   4.0    17.5     4.0             20.5
4           40.0    24.5           5.0  35.5    17.5    35.0             20.5
5           14.0    24.5           6.0  26.0    39.0    35.0             42.0
6           32.0    24.5           7.0  43.5     6.0    35.0             13.0
7           18.0    24.5           8.0  30.0    39.0    35.0             42.0
8           39.0    24.5           9.0  10.0    39.0    10.5             42.0
9           37.0    24.5          10.0  43.5    27.5    35.0             30.5
10           4.0    24.5          11.0  48.0    27.5    45.0             30.5
11          34.0    24.5          12.0  43.5    27.5    19.5             30.5
12          48.0    24.5          13.0  20.0    17.5    19.5             20.5
13          38.0    24.5          14.0  22.5    27.5    10.5             30.5
14          19.0    24.5          15.0  17.0    17.5    10.5             20.5
15          43.0    24.5          16.0   8.5     NaN     NaN              1.0
16          36.0    24.5          17.0  20.0     6.0    19.5              7.5
17          20.0    24.5          18.0  13.5    27.5    19.5             30.5
18           9.0    24.5          19.0   5.0     6.0     4.0              7.5
19           8.0    24.5          20.0  35.5    39.0    35.0             42.0
20          24.0    24.5          21.0  22.5    17.5    35.0             20.5
21          35.0    24.5          22.0  13.5    39.0    35.0             42.0
22          21.0    24.5          23.0  13.5    17.5    35.0             20.5
23          46.0    24.5          24.0  30.0     6.0     NaN              7.5
24           5.0    24.5          25.0  43.5     6.0    10.5              7.5
25           2.0    24.5          26.0  30.0    39.0    35.0             42.0
26          16.0    24.5          27.0  35.5    11.0     NaN             13.0
27          27.0    24.5          28.0  35.5    27.5    35.0             30.5
28          17.0    24.5          29.0  18.0    11.0    35.0             13.0
29           6.0    24.5          30.0   6.5    17.5     1.0             20.5
30          23.0    24.5          31.0  20.0    27.5    35.0             30.5
31          13.0    24.5          32.0  35.5    17.5    19.5             20.5
32           1.0    24.5          33.0   1.5     NaN     4.0              2.0
33          44.0    24.5          34.0  13.5     1.5     4.0              3.5
34          25.0    24.5          35.0  26.0    39.0    35.0             42.0
35          45.0    24.5          36.0  13.5    27.5    19.5             30.5
36          28.0    24.5          37.0  26.0    39.0    19.5             42.0
37          12.0    24.5          38.0  35.5    39.0    19.5             42.0
38          11.0    24.5          39.0   1.5    11.0    35.0             13.0
39           3.0    24.5          40.0  43.5     1.5    10.5              3.5
40          29.0    24.5          41.0  35.5    39.0    35.0             42.0
41          10.0    24.5          42.0  13.5    17.5    35.0             20.5
42          31.0    24.5          43.0  43.5     6.0    35.0             13.0
43          26.0    24.5          44.0  43.5    39.0    10.5             42.0
44          33.0    24.5          45.0  26.0    17.5    19.5             20.5
45          22.0    24.5          46.0  35.5    39.0    35.0             42.0
46          42.0    24.5          47.0  26.0    27.5    19.5             30.5
47           7.0    24.5          48.0   3.0    39.0    19.5             42.0

    Assignment 1  Assignment 2  Best of Assignments  Total Sessional (50)  \
0           10.5           9.0                 17.5                  42.0
1           24.0          21.5                 33.0                   8.0
2           24.0          21.5                 33.0                   9.0
3            NaN           1.0                  2.0                   4.0
4           10.5           9.0                 17.5                  29.5
5           24.0          21.5                 33.0                  35.0
6           24.0          21.5                 33.0                  35.0
7           24.0          21.5                 33.0                  42.0
8           10.5           9.0                 17.5                  14.0
9           24.0           NaN                 10.0                  35.0
10          24.0           NaN                 10.0                  47.0
11           2.0           NaN                  3.0                  24.5
12          24.0          21.5                 33.0                  20.5
13          24.0          21.5                 33.0                  27.0
14           5.5           5.0                 10.0                  12.0
15           NaN           NaN                  1.0                   1.0
16          10.5           9.0                 17.5                  14.0
17          39.5          34.0                 46.0                  17.5
18          24.0          21.5                 33.0                   7.0
19          24.0          21.5                 33.0                  47.0
20          10.5           9.0                 17.5                  20.5
21          39.5          34.0                 46.0                  20.5
22          10.5           NaN                  6.0                  10.5
23          24.0          21.5                 33.0                  24.5
24          39.5          34.0                 46.0                  35.0
25          24.0          21.5                 33.0                  42.0
26           5.5           5.0                 10.0                  24.5
27          24.0          21.5                 33.0                  42.0
28          39.5          34.0                 46.0                  17.5
29           5.5           NaN                  4.0                   6.0
30          39.5           NaN                 17.5                  20.5
31          45.0           NaN                 33.0                  35.0
32          24.0          21.5                 33.0                   2.0
33          24.0          21.5                 33.0                  10.5
34          24.0          21.5                 33.0                  35.0
35           NaN          21.5                 33.0                  16.0
36          39.5           NaN                 17.5                  29.5
37          39.5           NaN                 17.5                  42.0
38           2.0           2.5                  6.0                   3.0
39          39.5          34.0                 46.0                  29.5
40          24.0          21.5                 33.0                  47.0
41          24.0          21.5                 33.0                  14.0
42          24.0          21.5                 33.0                  35.0
43           5.5           5.0                 10.0                  42.0
44          39.5           NaN                 17.5                  24.5
45          39.5           NaN                 17.5                  42.0
46          24.0          21.5                 33.0                  29.5
47           2.0           2.5                  6.0                   5.0

    Final (50)  Total (100)  Grade
0         19.0         26.0   16.5
1          5.5          7.0   43.0
2         29.0         16.5   31.0
3         14.0          5.5   43.0
4         36.5         38.5   16.5
5         22.5         29.0   16.5
6         29.0         35.0   16.5
7         42.5         44.0    4.5
8         16.5         14.0   31.0
9         42.5         43.0    4.5
10        46.5         47.5    4.5
11        39.5         37.0   16.5
12        34.5         33.5   16.5
13        19.0         22.5   31.0
14        26.0         19.0   31.0
15         NaN          1.0   43.0
16        39.5         31.5   16.5
17        31.5         26.0   16.5
18        26.0         12.5   31.0
19        46.5         47.5    4.5
20        31.5         29.0   16.5
21         8.5         12.5   31.0
22        14.0         10.0   43.0
23        10.0         15.0   31.0
24        34.5         38.5   16.5
25        44.0         45.5    4.5
26        16.5         19.0   31.0
27        21.0         29.0   16.5
28         5.5         10.0   43.0
29         2.0          3.5   43.0
30        33.0         31.5   16.5
31        26.0         33.5   16.5
32         1.0          2.0   43.0
33         3.5          8.0   43.0
34        45.0         45.5    4.5
35        24.0         21.0   31.0
36        22.5         26.0   16.5
37        29.0         36.0   16.5
38         3.5          3.5   43.0
39        19.0         24.0   31.0
40        39.5         42.0    4.5
41         8.5         10.0   43.0
42        14.0         22.5   31.0
43        36.5         40.0   16.5
44        11.5         16.5   31.0
45        39.5         41.0    4.5
46        11.5         19.0   31.0
47         7.0          5.5   43.0

In [26]:
print(UNV.fillna=0)

SyntaxError: keyword can't be an expression (<ipython-input-26-dbd8256c921c>, line 1)

### 6. Display the top 10 rows

In [43]:
print(UNV.iloc[[1],[10]])

   Total Sessional (50)
1                    32

In [42]:
print(UNV.iat([0],[2]))

TypeError: __call__() takes from 1 to 2 positional arguments but 3 were given

In [31]:
UNV[0:11]

,Student Code,Degree,Student Name,Mid,Quiz 1,Quiz 2,Best of Quizzes,Assignment 1,Assignment 2,Best of Assignments,Total Sessional (50),Final (50),Total (100),Grade
0,022-14-19987,BS(CS),Abdul Basit,28,8.0,3.0,8,7.0,9.0,9,45,25.0,70,B
1,022-14-110233,BS(CS),Adeel Ahmed,17,NaN,5.0,5,8.0,10.0,10,32,18.0,50,F
2,022-14-110585,BS(CS),Afrah Zareen,18,5.0,2.0,5,8.0,10.0,10,33,30.0,63,C
3,022-14-19718,BS(CS),Ahmed Ali Raza,14,7.0,2.0,7,NaN,2.0,2,23,23.0,46,F
4,022-14-110648,BS(CS),Ahsan Ali Vohra,27,7.0,6.0,7,7.0,9.0,9,43,34.0,77,B
5,022-14-110232,BS(CS),Ameer Hamza,25,9.0,6.0,9,8.0,10.0,10,44,27.0,71,B
6,022-14-110588,BS(CS),Anas Ali Khan,28,5.0,6.0,6,8.0,10.0,10,44,30.0,74,B
7,022-14-110388,BS(CS),Aneebullah Niazi,26,9.0,6.0,9,8.0,10.0,10,45,40.0,85,A
8,022-14-110601,BS(CS),Areesha Sohail,19,9.0,4.0,9,7.0,9.0,9,37,24.0,61,C
9,022-14-110599,BS(CS),Arsalan,28,8.0,6.0,8,8.0,NaN,8,44,40.0,84,A
10,022-14-110214,BS(CS),Fatima Haider Warsi,30,8.0,7.0,8,8.0,NaN,8,46,45.0,91,A

In [54]:
UNV.loc[[5], ['Quiz 1']]

   Quiz 1
5     9.0

In [61]:
k=pd.DataFrame({'A' : ['X', 'Y'], 
                        'B' : 1, 
                        'C' : [2, 3]})
k
#k.values

   A  B  C
0  X  1  2
1  Y  1  3

### 7. Display the last 10 rows

In [63]:
UNV.loc[10,'Assignment 1']

8.0

In [71]:
UNV.loc[10,:]

Student Code                  022-14-110214
Degree                               BS(CS)
Student Name            Fatima Haider Warsi
Mid                                      30
Quiz 1                                    8
Quiz 2                                    7
Best of Quizzes                           8
Assignment 1                              8
Assignment 2                            NaN
Best of Assignments                       8
Total Sessional (50)                     46
Final (50)                               45
Total (100)                              91
Grade                                     A
Name: 10, dtype: object

In [73]:
UNV.loc[12,'Student Name']

'Hafiza Tooba Akbani'

In [76]:
UNV.iloc[12,:]

Student Code                  022-15-110994
Degree                               BS(CS)
Student Name            Hafiza Tooba Akbani
Mid                                      23
Quiz 1                                    7
Quiz 2                                    5
Best of Quizzes                           7
Assignment 1                              8
Assignment 2                             10
Best of Assignments                      10
Total Sessional (50)                     40
Final (50)                               33
Total (100)                              73
Grade                                     B
Name: 12, dtype: object

In [84]:
UNV.iloc[1,2:]

Student Name            Adeel Ahmed
Mid                              17
Quiz 1                          NaN
Quiz 2                            5
Best of Quizzes                   5
Assignment 1                      8
Assignment 2                     10
Best of Assignments              10
Total Sessional (50)             32
Final (50)                       18
Total (100)                      50
Grade                             F
Name: 1, dtype: object

### 8. Display only the odd rows

### 9. Display only those students who got failed in examination

### 10. Find out the basic statistical info about data

### 11. How many students got A, B, C, F?

### 12. What are the mean scores for students who got A, B, C, F?